### ISSUE TITLE
polybar icons aren't working

### ISSUE THREAD

**Issue by tamirazrab** [totoro-ghost/dotfiles#3]
![11](https://user-images.githubusercontent.com/38686510/133358861-febfd63b-48ce-473e-8be8-6203d2023928.png)

installed feather font, all other fonts are also complete don't know why it isn't working.

**Comment by Keyitdev** [comment]
Possible solutions:
1. Try to install font from here: https://github.com/AT-UI/feather-font/blob/master/src/fonts/feather.ttf.
2. Try to copy font to other location (
-  /usr/share/fonts/ system fonts
-  /usr/local/share/fonts  standard location for fonts
- ~/.local/share/fonts/ fonts installed with Font Manager)
3. Make sure the font is properly installed
for example run something like this:
```
#!/bin/bash
for range in $(fc-match --format='%{charset}\n' "Feather"); do
    for n in $(seq "0x${range%-*}" "0x${range#*-}"); do
        n_hex=$(printf "%04x" "$n")
        # using \U for 5-hex-digits     
        printf "%-5s\U$n_hex\t" "$n_hex"
        count=$((count + 1))            
        if [ $((count % 10)) = 0 ]; then
            printf "\n"
        fi
    done
done       
printf "\n"
```
If everything works fine you should get something like this:
![image](https://user-images.githubusercontent.com/70140437/133491774-880bbfbd-6681-45ca-b355-8bc58ed1e318.png)

**Comment by tamirazrab** [comment]
![1111](https://user-images.githubusercontent.com/38686510/133523976-95c4d519-a201-49f1-8c24-7c8939783456.png)

Moved font to specified location. Still no luck.

**Comment by Keyitdev** [comment]
I don't know. Maybe try to run polybar with console log.
`polybar main --config=~/.config/polybar/config_i3.ini`
And show me the output.
My output (fonts):
```
notice: Loaded font "Iosevka Nerd Font:size=14" (name=Iosevka, offset=4, file=/home/username/.local/share/fonts/Iosevka-Nerd-Font.ttf)
notice: Loaded font "Iosevka Nerd Font:style=Medium:size=20" (name=Iosevka, offset=4, file=/home/username/.local/share/fonts/Iosevka-Nerd-Font.ttf)
notice: Loaded font "feather:size=15" (name=feather, offset=3, file=/home/username/.local/share/fonts/Feather.ttf)
```

**Comment by tamirazrab** [comment]
`notice: Parsing config file: /home/tamir/.config/polybar/config_i3.ini
notice: Loaded font "Iosevka Nerd Font:size=13" (name=Iosevka, offset=4, file=/usr/share/fonts/TTF/Iosevka Nerd Font Complete.ttf)
notice: Loaded font "Iosevka Nerd Font:style=Medium:size=15" (name=Iosevka, offset=4, file=/usr/share/fonts/TTF/Iosevka Medium Nerd Font Complete.ttf)
notice: Loaded font "feather:size=15" (name=feather, offset=3, file=/home/tamir/.fonts/feather.ttf)`

Though thank you for your help, I actually manually copied icons from terminal and added some to bar.

**Comment by Keyitdev** [comment]
Yes, my last idea was to suggest manually copying the fonts from the terminal. But I wonder why you have different unicodes. I don't know much about fonts. Anyway, I'm glad I could help you. Cheers.

**Comment by totoro-ghost** [comment]
@Deerrorer thanks for helping with the issue. @tamirazrab  please try [this](https://github.com/adi1090x/polybar-themes/blob/master/fonts/feather.ttf?raw=true) font, this is modified version. I'll fix the link README.

**Comment by totoro-ghost** [comment]
I searched on web but I cannot find the source of the font link i gave (the adi repo one) (every font i found was somewhat different),  maybe he made that himself. 

In case you want to make your own `.tff` here is their official repo - [https://github.com/feathericons/feather](https://github.com/feathericons/feather)
