### ISSUE TITLE
rofi notification not showing clock 

### ISSUE THREAD

**Issue by raexera** [totoro-ghost/dotfiles#5]
`Notification Center` doens't showing a clock, how to fix it?

**Comment by totoro-ghost** [comment]
It is overflowing, so either you can increase the size for text area using rofi config OR

[https://github.com/totoro-ghost/dotfiles/blob/2c8b74c781ab2020cf285e950c1f8aa126ac0593/.config/rofi/rofi-notification/rofi_notif_center.sh#L75](https://github.com/totoro-ghost/dotfiles/blob/2c8b74c781ab2020cf285e950c1f8aa126ac0593/.config/rofi/rofi-notification/rofi_notif_center.sh#L75)

You can reduce this number, and then it will show up. like `app_spaces=$(printf %-20.20s "$a")`.

**Comment by rxyhn** [comment]
`solved` thanks!
